apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockifai-spark
  namespace: stockifai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockifai-spark
  template:
    metadata:
      labels:
        app: stockifai-spark
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.36
        command:
        - 'sh'
        - '-c'
        - |
          echo "Waiting for Kafka to be ready..."
          until nc -z kafka.stockifai.svc.cluster.local 9092; do
            echo "Kafka not ready, waiting..."
            sleep 5
          done
          echo "Kafka is ready!"
      - name: wait-for-schema-registry
        image: busybox:1.36
        command:
        - 'sh'
        - '-c'
        - |
          echo "Waiting for Schema Registry to be ready..."
          until nc -z schema-registry-svc.stockifai.svc.cluster.local 8081; do
            echo "Schema Registry not ready, waiting..."
            sleep 5
          done
          echo "Schema Registry is ready!"
      containers:
      - name: stockifai-spark
        image: localhost:5000/stockifai/spark:latest
        env:
        - name: SPARK_DRIVER_MEMORY
          value: 512m
        - name: SPARK_EXECUTOR_MEMORY
          value: 512m
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.stockifai.svc.cluster.local:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://schema-registry-svc.stockifai.svc.cluster.local:8081"
        - name: INFLUXDB_URL
          value: "http://influxdb.stockifai.svc.cluster.local:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: stockifai-secrets
              key: INFLUXDB_TOKEN
        envFrom:
        - secretRef:
            name: stockifai-secrets
        volumeMounts:
        - name: astra-bundle
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            memory: "800Mi"
            cpu: "500m"
          limits:
            memory: "1200Mi"
            cpu: "1"
      volumes:
      - name: astra-bundle
        secret:
          secretName: astra-bundle
