apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockifai-stream
  namespace: stockifai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockifai-stream
  template:
    metadata:
      labels:
        app: stockifai-stream
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.36
        command: 
          - 'sh'
          - '-c'
          - |
            echo "Waiting for Kafka to be ready..."
            until nc -z kafka.stockifai.svc.cluster.local 9092; do
              echo "Kafka not ready, waiting..."
              sleep 5
            done
            echo "Kafka is ready!"
      - name: wait-for-schema-registry
        image: busybox:1.36
        command: 
          - 'sh'
          - '-c'
          - |
            echo "Waiting for Schema Registry to be ready..."
            until nc -z schema-registry-svc.stockifai.svc.cluster.local 8081; do
              echo "Schema Registry not ready, waiting..."
              sleep 5
            done
            echo "Schema Registry is ready!"
      containers:
      - name: stockifai-stream
        image: localhost:5000/stockifai/stream:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k3s-production"
        - name: KAFKA_BOOTSTRAP_SERVERS_K3S
          value: "kafka.stockifai.svc.cluster.local:9092"
        - name: SCHEMA_REGISTRY_URL_K3S
          value: "http://schema-registry-svc.stockifai.svc.cluster.local:8081"
        envFrom:
        - secretRef:
            name: stockifai-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /stream/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 20
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /stream/actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /stream/actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stockifai-stream
  namespace: stockifai
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: stockifai-stream
