apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockifai-api
  namespace: stockifai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockifai-api
  template:
    metadata:
      labels:
        app: stockifai-api
    spec:
      containers:
      - name: stockifai-api
        image: localhost:5000/stockifai/api:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k3s-production"
        - name: INFLUXDB_URL
          value: "http://influxdb.stockifai.svc.cluster.local:8086"
        envFrom:
        - secretRef:
            name: stockifai-secrets
        volumeMounts:
        - name: astra-bundle
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10
      volumes:
      - name: astra-bundle
        secret:
          secretName: astra-bundle
---
apiVersion: v1
kind: Service
metadata:
  name: stockifai-api
  namespace: stockifai
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: stockifai-api
