apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockifai-stream
  namespace: stockifai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockifai-stream
  template:
    metadata:
      labels:
        app: stockifai-stream
    spec:
      containers:
      - name: stockifai-stream
        image: localhost:5000/stockifai/stream:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k3s-production"
        - name: APP_SCHEMA-REGISTRY-URL
          value: "http://schema-registry.stockifai.svc.cluster.local:8081"
        - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
          value: "http://schema-registry.stockifai.svc.cluster.local:8081"
        - name: KAFKA_BOOTSTRAP_SERVERS_K3S
          value: "kafka:9092"
        - name: SCHEMA_REGISTRY_URL_K3S
          value: "http://schema-registry:8081"
        envFrom:
        - secretRef:
            name: stockifai-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /stream/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /stream/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: stockifai-stream
  namespace: stockifai
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: stockifai-stream
