name: stockifai
description: StockiFAI Real-time Stock Monitor Flutter App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  dio: ^5.3.2
  
  # State management
  provider: ^6.1.1
  
  # Charts
  fl_chart: ^1.0.0
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utilities
  intl: ^0.18.1
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  intl: ^0.18.1