global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/rules/rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api:8080"]

  - job_name: "stream"
    metrics_path: /stream/actuator/prometheus
    static_configs:
      - targets: ["stream:8080"]
